# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=root" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/etc" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=etc" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=log" ];
    };

  fileSystems."/data/mc" =
    { device = "/dev/disk/by-uuid/0e560b25-de29-4728-86d6-ca46b42c3f9b";
      fsType = "btrfs";
      options = [ "subvol=mc" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/34CA-5A06";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
