path-format /data/music/{{ artists .Release.Artists | sort | join ", " | safepath }}/{{ .Release.Title | safepath }} ({{ .Release.ReleaseGroup.FirstReleaseDate.Year }}){{ if not (eq .ReleaseDisambiguation "") }} [{{ .ReleaseDisambiguation | safepath }}]{{ end }}/{{ pad0 2 .TrackNum }} {{ artistsString .Track.Artists | safepath }} - {{ .Track.Title | safepath }}{{ .Ext }}

web-api-key verycoolpassword

addon replaygain
addon lyrics lrclib musixmatch genius

